### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by bated54** [Fytex/H43#1]
non mi fa scaricare il file mi dice che contiene un virus

**Comment by Fytex** [comment]
If you on google chrome press CTRL+J to open the downloads. There you can select to download it anyways.
If when executing it still says it's a virus than your only option is to disable anti-virus.

Note: This is a open source project so you have the code right next to it if you are afraid of it. The reason why it is being detected as a virus (fake positive) its because of pyinstaller (used to make an executable out of a python script).

Greetings,
Fytex
