### ISSUE TITLE
Trojan Alert for H43 BOT (32 bits).exe

### ISSUE THREAD

**Issue by XeroSaber0825** [Fytex/H43#3]
Downloaded master branch. H43 BOT (32 bits).exe is recognized as a trojan. Is file the dangerous?

**Comment by Fytex** [comment]
No, it is completely safe. You have the whole source code next to it if you want to read or run from it instead of executing the  .exe.

Why is it recognized as a trojan? I used _pyinstaller_ to compile the code into an executable. That is recognized as a virus by some antivirus. If you search on google something like "Pyinstaller seen as virus", you will have a better explanation.

**Comment by logicguy1** [comment]
Its just not been signed by Microsoft

**Comment by FailedCoder23** [comment]
it says Trojan:Win32/Zpevdo.B

**Comment by logicguy1** [comment]
A lot of software gets marked as Trojans by microsoft
They want to control the application market, thats why i like linux
